import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    slug: 'personality',
    name_uk: 'Гороскоп особистості',
    category: 'purpose',
    description_uk: 'Що ваша доля, призначення, як досягти успіху',
    value_props_uk: [
      'Глибокий аналіз вашої натальної карти',
      'Ваше справжнє покликання та таланти',
      'Як максимізувати свій потенціал',
      'Персональні рекомендації для успіху',
    ],
    price_usd: 29.99,
    icon: 'sparkles',
    sort_order: 1,
  },
  {
    slug: 'talent',
    name_uk: 'Звіт талантів',
    category: 'purpose',
    description_uk: 'Ваші приховані таланти та як їх розкрити',
    value_props_uk: [
      'Природні здібності за натальною картою',
      'Як розвивати приховані таланти',
      'Найкращі сфери для реалізації',
      'Стратегія розкриття потенціалу',
    ],
    price_usd: 24.99,
    icon: 'gem',
    sort_order: 2,
  },
  {
    slug: 'love',
    name_uk: 'Любовний гороскоп',
    category: 'love',
    description_uk: 'Де і коли ви зустрінете кохання',
    value_props_uk: [
      'Ваш тип ідеального партнера',
      'Найкращі періоди для знайомств',
      'Як побудувати гармонійні стосунки',
      'Астрологічні ключі до кохання',
    ],
    price_usd: 24.99,
    icon: 'heart',
    sort_order: 3,
  },
  {
    slug: 'marriage',
    name_uk: 'Коли я одружуся?',
    category: 'love',
    description_uk: 'Прогноз щодо шлюбу',
    value_props_uk: [
      'Сприятливі періоди для шлюбу',
      'Астрологічна сумісність з партнером',
      'Ключові транзити для стосунків',
      'Прогноз розвитку відносин',
    ],
    price_usd: 19.99,
    icon: 'ring',
    sort_order: 4,
  },
  {
    slug: 'love-compatibility',
    name_uk: 'Сумісність кохання',
    category: 'love',
    description_uk: 'Детальний синастрійний звіт',
    value_props_uk: [
      'Повний синастрійний аналіз',
      'Сильні та слабкі сторони пари',
      'Рекомендації для гармонії',
      'Прогноз розвитку стосунків',
    ],
    price_usd: 24.99,
    icon: 'heart-handshake',
    sort_order: 5,
  },
  {
    slug: 'conception',
    name_uk: 'Календар зачаття',
    category: 'children',
    description_uk: 'Найкращі дні для зачаття',
    value_props_uk: [
      'Сприятливі астрологічні періоди',
      'Місячні цикли та фертильність',
      'Персоналізований календар',
      'Рекомендації на основі транзитів',
    ],
    price_usd: 19.99,
    icon: 'calendar-heart',
    sort_order: 6,
  },
  {
    slug: 'pregnancy',
    name_uk: 'Прогноз вагітності',
    category: 'children',
    description_uk: 'Астрологічний прогноз вагітності',
    value_props_uk: [
      'Сприятливі періоди для вагітності',
      'Астрологічний прогноз перебігу',
      'Характер майбутньої дитини',
      'Рекомендації для здорової вагітності',
    ],
    price_usd: 19.99,
    icon: 'baby',
    sort_order: 7,
  },
  {
    slug: 'children',
    name_uk: 'Дитячий гороскоп',
    category: 'children',
    description_uk: 'Гороскоп для батьків про дитину',
    value_props_uk: [
      'Характер та темперамент дитини',
      'Таланти та здібності',
      'Рекомендації для виховання',
      'Як підтримати розвиток дитини',
    ],
    price_usd: 19.99,
    icon: 'smile',
    sort_order: 8,
  },
  {
    slug: 'health',
    name_uk: "Звіт здоров'я",
    category: 'health',
    description_uk: "Вразливі зони здоров'я за натальною картою",
    value_props_uk: [
      'Слабкі зони за натальною картою',
      'Рекомендації щодо профілактики',
      'Найкращі періоди для лікування',
      "Астрологічний погляд на здоров'я",
    ],
    price_usd: 24.99,
    icon: 'activity',
    sort_order: 9,
  },
  {
    slug: 'calendar',
    name_uk: 'Персональний календар',
    category: 'future',
    description_uk: 'Щоденні поради на основі транзитів',
    value_props_uk: [
      'Персоналізований щоденний прогноз',
      'Сприятливі та несприятливі дні',
      'Планування важливих подій',
      'Транзити планет для вас особисто',
    ],
    price_usd: 29.99,
    icon: 'calendar',
    sort_order: 10,
  },
  {
    slug: 'monthly',
    name_uk: 'Прогноз на місяць',
    category: 'future',
    description_uk: 'Детальний місячний прогноз',
    value_props_uk: [
      'Детальний прогноз на кожен тиждень',
      'Ключові дати та події місяця',
      'Рекомендації для кожної сфери',
      'Місячні транзити та їх вплив',
    ],
    price_usd: 14.99,
    icon: 'calendar-days',
    sort_order: 11,
  },
  {
    slug: '3-years',
    name_uk: 'Прогноз на 3 роки',
    category: 'future',
    description_uk: 'Довгостроковий прогноз',
    value_props_uk: [
      'Стратегічний прогноз на 3 роки',
      'Ключові поворотні моменти',
      'Сприятливі періоди для дій',
      'Довгострокові планетарні впливи',
    ],
    price_usd: 39.99,
    icon: 'telescope',
    sort_order: 12,
  },
  {
    slug: 'finance',
    name_uk: 'Фінансовий успіх',
    category: 'money',
    description_uk: 'Як покращити фінансове становище',
    value_props_uk: [
      'Фінансовий потенціал за картою',
      'Найкращі періоди для заробітку',
      'Ризики та як їх уникнути',
      'Стратегія фінансового зростання',
    ],
    price_usd: 24.99,
    icon: 'coins',
    sort_order: 13,
  },
  {
    slug: 'career',
    name_uk: "Кар'єрний гороскоп",
    category: 'money',
    description_uk: "Кар'єрне призначення та поради",
    value_props_uk: [
      "Ваше кар'єрне призначення",
      'Найкращі сфери для реалізації',
      "Періоди кар'єрного зростання",
      'Рекомендації для професійного успіху',
    ],
    price_usd: 24.99,
    icon: 'briefcase',
    sort_order: 14,
  },
  {
    slug: 'business',
    name_uk: 'Бізнес-гороскоп',
    category: 'money',
    description_uk: 'Астрологічний бізнес-аналіз',
    value_props_uk: [
      'Підприємницький потенціал',
      'Найкращий час для старту',
      'Партнерство та співпраця',
      'Стратегія бізнес-розвитку',
    ],
    price_usd: 29.99,
    icon: 'trending-up',
    sort_order: 15,
  },
  {
    slug: '2026',
    name_uk: 'Гороскоп на 2026',
    category: 'future',
    description_uk: 'Річний прогноз',
    value_props_uk: [
      'Повний прогноз на 2026 рік',
      'Ключові дати та події року',
      'Рекомендації для кожного кварталу',
      'Як максимально використати рік',
    ],
    price_usd: 19.99,
    icon: 'calendar-range',
    sort_order: 16,
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return PRODUCTS.filter((p) => p.category === category).sort((a, b) => a.sort_order - b.sort_order);
}

export function getAllProductSlugs(): string[] {
  return PRODUCTS.map((p) => p.slug);
}
